### ISSUE TITLE
UI Bug / CORS / Axios issue

### ISSUE THREAD

**Issue by ryuzaki01** [NFTEarth/marketplace-v2#40]
CORS and Axios in UI causing bug. 

![Image](https://user-images.githubusercontent.com/29180454/221018520-24163616-40ea-44dd-9575-e7d2330e2381.png)

**Comment by westonnelson** [comment]
![Image](https://user-images.githubusercontent.com/29180454/221029937-99bb2fbd-7d75-4e76-b2bc-6497cb46160d.png)

**Comment by ryuzaki01** [comment]
the commit de59fadda8777770e0a58d8ee67829570d21e897 resolved the issue
