### ISSUE TITLE
Explain Rarity source

### ISSUE THREAD

**Issue by 0xadventurer** [NFTEarth/marketplace-v2#58]
Our rarity of any/all collections is different than OS, which is fine (I guess) unless we explain source we use! 

OR maybe even better - if possible - us same as OS

![Image](https://user-images.githubusercontent.com/126287847/221440137-8c9d9210-db06-45b8-8d98-f805ac18a9d9.png)

In many, many cases people are buying based on rarity - we will have a lot of issues later if either one or another above will be done

**Comment by westonnelson** [comment]
Planning to use Rarity toolkit.
